apiVersion: v2
appVersion: 2.5.1
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.logo: https://s.giantswarm.io/app-icons/flux/2/logo_dark.svg
  io.giantswarm.application.restrictions.cluster-singleton: 'true'
  io.giantswarm.application.team: honeybadger
  io.giantswarm.application.two-step-install: 'true'
description: |
  Flux is a collection of tools for keeping Kubernetes clusters in sync
  with sources of configuration (like Git repositories), and automating
  updates to configuration when there is new code to deploy.
engine: gotpl
home: https://github.com/giantswarm/flux-app
icon: https://s.giantswarm.io/app-icons/flux/2/icon_light.svg
keywords:
  - gitops
  - flux
name: flux-app
sources:
  - https://github.com/fluxcd/flux2
type: application
version: 1.8.0
